version: '3.9'

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500" # Consul UI
      - "8600:8600/udp" # DNS queries
    networks:
      - app-network
    command: agent -server -bootstrap -ui -client=0.0.0.0

  service-registry:
    image: service-registry-image
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - consul
    networks:
      - app-network
    environment:
      CONSUL_HOST: consul # Use the 'consul' container name
      CONSUL_PORT: 8500

  config-server:
    image: config-server-image
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - consul
    networks:
      - app-network
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

  api-gateway:
    image: api-gateway-image
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - config-server
      - consul
    networks:
      - app-network
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

networks:
  app-network:
    driver: bridge
