version: '3.9'

services:
  app-registry:
    image: app-registry-image
    build:
      context: ./app-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - app-network

  config-server:
    image: config-server-image
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - app-network

  api-gateway:
    image: api-gateway-image
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - app-registry
      - config-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
