filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    json.message_key: log
    json.keys_under_root: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "admin" # Optional, depending on your setup
  password: "admin" # Optional, depending on your setup

setup.kibana:
  host: "http://kibana:5601"
