global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'consul'
    consul_sd_configs:
      - server: 'consul:8500'
        scheme: 'http'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        action: keep
        regex: '.*' # Include all services

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'config-server'
    static_configs:
      - targets: [ 'config-server:8888' ]

  - job_name: 'service-registry'
    static_configs:
      - targets: [ 'service-registry:8761' ]
