spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: consul-server-client  # Consul container name
      port: 8500
      discovery:
        enabled: true
        service-name: api-gateway
        prefer-ip-address: true
        tags: ["gateway", "api"]
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service  # Load-balanced route for the auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<path>.*), /$\{path}
          metadata:
            api-docs-enabled: true
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "http://localhost:4200"
          allowedHeaders: "*"
          allowedMethods:
            - GET
            - POST
            - PATCH
            - DELETE
    httpclient:
      connect-timeout: 2000
      response-timeout: 90s
    discovery:
      enabled: true
      locator:
        enabled: true
        lowerCaseServiceId: true

logging:
  level:
    reactor:
      netty:
        http:
          client: INFO
    org:
      springframework:
        cloud:
          gateway: INFO

# Gateway Host Context Path
api-gateway:
  context-path: /gateway-dev

server:
  servlet:
    context-path: ${api-gateway.context-path}
  display-name: api-gateway
  port: 8080

management:
  health:
    discovery:
      enabled: true
    consul:
      enabled: true
