spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/Users/amieldelosreyes/Desktop/Software Engineering/Amiel-Aljon Company/amiel-aljon-company/config-server/config
#        git: for remote git config server
#          url:
#          username:
#          password:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost

server:
  port: 8888

